# Generated by Django 3.1.1 on 2020-10-07 09:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletters',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 10, 7, 9, 58, 17, 95500, tzinfo=utc), max_length=45),
            preserve_default=False,
        ),
    ]
